# Generated by Django 3.2 on 2021-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='username',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='用户名称'),
        ),
    ]
