# Generated by Django 3.2 on 2021-05-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token', '0002_auto_20210508_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default='', max_length=64, verbose_name='用户TOKEN'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='username',
            field=models.CharField(default='', max_length=64, verbose_name='用户名称'),
        ),
        migrations.AlterUniqueTogether(
            name='authtoken',
            unique_together={('username', 'token')},
        ),
    ]
