# Generated by Django 3.2.2 on 2021-05-08 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=64, verbose_name='中文姓名')),
                ('perm_group', models.CharField(default='', max_length=64, verbose_name='权限属组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_perm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
