# Generated by Django 2.2.7 on 2019-12-16 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_group', models.CharField(choices=[('guest', 0), ('normal', 1), ('admin', 2)], default=0, max_length=16, verbose_name='权限属组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_perm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
