# Generated by Django 2.1.7 on 2019-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=8, unique=True, verbose_name='用户名称')),
                ('token', models.CharField(default='', max_length=64, unique=True, verbose_name='用户TOKEN')),
                ('sign_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('expired_time', models.IntegerField(default=86400, verbose_name='有效期限')),
            ],
        ),
    ]
