# Generated by Django 3.2 on 2021-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_availabletasks_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='expired_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='失效日期设置'),
        ),
    ]
