# Generated by Django 3.2.2 on 2021-05-08 08:04

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, verbose_name='用户')),
                ('api', models.CharField(default='', max_length=128, verbose_name='调用API')),
                ('action', models.CharField(default='', max_length=64, verbose_name='执行动作')),
                ('action_label', models.CharField(default='', max_length=128, verbose_name='执行动作label')),
                ('post_data', jsonfield.fields.JSONField(default={}, verbose_name='操作内容')),
                ('result', models.CharField(default='', max_length=16, verbose_name='操作结果')),
                ('message', models.TextField(default='', verbose_name='成功消息')),
                ('error_message', models.TextField(default='', verbose_name='失败消息')),
                ('operating_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
