# Generated by Django 3.0.6 on 2020-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_apicallingrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicallingrecord',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='apicallingrecord',
            name='action_label',
            field=models.CharField(default='', max_length=128, verbose_name='执行动作label'),
        ),
    ]
